[project]
name = "2024-yonsei-gdsc-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.2.0",
    "pandas>=2.2.3",
    "transformers>=4.47.1",
]
